a = int(input("Enter a value"))
b = int(input("Enter a value"))

print("Addition is:",a+b)
print("Substration is:",a-b)
print("Mul is:",a*b)
print("Div is:",a/b)
print("Floor Div:",a//b)
print("pow is",a**b)
print("Modules is:",a%b)
